services:
#    book.block.list:
#        class: "BookBundle\\Block\\ListBooksBlockService"
#        arguments:
#          - book.block.list
#          - '@templating'
#          - '@?doctrine'
#        tags:
#          - { name: sonata.block }
#
#    book.block.book_voting:
#        class: "BookBundle\\Block\\BookVotingBlockService"
#        arguments:
#          - book.block.book_voting
#          - '@templating'
#          - '@request_stack'
#          - '@book.entity_manager'
#        tags:
#          - { name: sonata.block }